### ISSUE TITLE
[BACK-TASK] 소셜유저 회원가입 시 프로필 이미지 추가 요청

### ISSUE THREAD

**Issue by 97970z** [Selody-project/Backend#102]
### 설명

현재 `소셜 유저 회원가입`할 때  [joinSocialUser](https://github.com/Selody-project/Backend/blob/33fe17aa607b215b250b0bc50a79656148447e57/src/controllers/auth.js#L77) 에서 `nickname`, `provider`, `snsId`가 저장되고 있습니다. 
여기에 `profileImage` 항목 추가 부탁드립니다.
(소셜 유저들의 프로필 이미지를 대체하기 위함)
```
await User.create({
        nickname: req.body.nickname,
        profileImage: req.body.profile_image, // 프로필 이미지 주소 추가
        provider: 'NAVER',
        snsId: req.body.id,
});
```

### 링크

**Pre-requisite**: [Link to pre-req task](https://github.com/xERN-shareANDcommunity/Backend)

**Comment by Taehoya** [comment]
https://github.com/Selody-project/Backend/issues/58 
중복항목이라 issue close 하겠습니다.!
