### ISSUE TITLE
[BACK-TASK] 그룹에 구성된 유저 조회 질문

### ISSUE THREAD

**Issue by 97970z** [Selody-project/Backend#112]
### 설명

![스크린샷 2023-06-28 204837](https://github.com/Selody-project/Backend/assets/71217361/0b3b375b-fc30-414d-9202-89c99aafa3c9)
위 부분을 구현 중인데 `그룹을 선택하면 해당 그룹의 인원`을 보여주는 부분이 있습니다.
`groupId`를 가지고 어떤 엔드포인트로 요청을 보내야 그룹에 포함된 유저들 정보를 받아올 수 있을까요?

### 링크

**Pre-requisite**: [Link to pre-req task](https://github.com/xERN-shareANDcommunity/Backend)

**Comment by Taehoya** [comment]
https://github.com/Selody-project/Backend/issues/114 티켓 만들었습니다.
