### ISSUE TITLE
[BACK-TASK] `GET api/user/{user-id}/calendar?date=?`

### ISSUE THREAD

**Issue by GGANCC1** [Selody-project/Backend#50]
### Description
- Implement GET api/user/{user-id}/calendar?date=?
- 한달 단위의 User 개인 일정 조회
- 기존의 코드를 raw query로 변경
![image](https://github.com/Selody-project/Backend/assets/81506668/d36cf591-5d1f-4638-8b9b-1d5bb22da265)

**Comment by muttaqin1** [comment]
hey! @GGANCC1, can i contribute on this issue?

**Comment by GGANCC1** [comment]
ㅁㄴㅇㅇㄴㅁ
