### ISSUE TITLE
[BACK-TASK] 유저 정보 업데이트 라우터 요청

### ISSUE THREAD

**Issue by 97970z** [Selody-project/Backend#54]
### Description

아래와 같이 변경된 nickname, password를 보낼 것 같습니다.

```
const response = await customFetch.put(`/api/auth/updateProfile`, { newNickname: nickname, newPassword: password });

```
### Link

**Pre-requisite**: [Link to pre-req task](https://github.com/xERN-shareANDcommunity/Backend)

**Comment by GGANCC1** [comment]
api/user/profile 엔드 포인트로 put request 라우터 만들어 놓겠습니다.
그리고 혹시 request 보내실 때 body에 { nickname, password } 이렇게 보내주실 수 있을까요.

**Comment by GGANCC1** [comment]
auth보다는 user쪽에 두는게 나을 것 같아요. api/user/profile 엔드 포인트로 put request 라우터 만들어 놓겠습니다.

**Comment by 97970z** [comment]
네 감사합니다~

**Comment by GGANCC1** [comment]
기능 구현은 끝났고, PR 작성중입니다. {nickname: "새로운 닉네임", password: "새로운 패스워드"} 으로 던져주시면 됩니다.
