### ISSUE TITLE
getUserPersonalSchedule

### ISSUE THREAD

**Issue by joseph0926** [Selody-project/Backend#95]
### 설명

/controllers/user.js - getUserPersonalSchedule

    const { startDateTime, endDateTime } = req.body;
    const start = moment.utc(startDateTime).toDate();
    const end = moment.utc(endDateTime).toDate();
    const schedule = await PersonalSchedule.getSchedule(user.userId, start, end);
    
    startDateTime과 endDateTime으로 리미트를 거신 이유는 뭔가요?
    또한 이러면 get이 아니라 post로 바꿔야하나요?
    
 참고
 
![sch01](https://github.com/Selody-project/Backend/assets/100750188/c2039786-a2aa-4f99-a3d1-2e86bc1d99b2)
![sch02](https://github.com/Selody-project/Backend/assets/100750188/e0ad7db7-fbf0-443d-8061-7b603142375c)

**Comment by GGANCC1** [comment]
1. startDateTime, endDateTime은 조회하고자 하는 `시간 구간`의 `시작점(startDateTime)`과 `종점(endDateTime)`을 의미합니다.
  일정 조회 시, 프론트 서버측에서는 `구하고 싶은 시간 구간`의 `시작점(startDateTime)`과 `종점(endDateTime)`을 각각 utc timezone로 변환한 뒤에 요청과 함께 보내주시면 됩니다. 그럼 백엔드 서버 측에서는 해당 구간의 일정들을 모아서 결과값으로 보내주게 됩니다.
예를 들어 `대한민국` 기준 4월 15일 하루 동안의 일정을 조회하고자 한다면 +9:00의 시차값이 계산된 값을 전달해 주시면 됩니다.  
이 경우, `startDateTime` 은 `2023-04-14 T15:00:00:00.000Z`, `endDateTime`은 `2023-04-15 T14:59:59.999Z`입니다. 
#44 해당 이슈의 개선방안 부분에 언급된 내용을 참고하시면 좋을 것 같습니다. 
> "예를들어 `대한민국`에 거주하고 있는 사용자가 `4월 일정`을 조회하고자 한다면, 서버 시간대인 `UTC timezone` 환경에서는 `2023-03-31 T15:00:00.000Z ~ 2023-04-30 T14:59:59.999Z` 구간의 일정을 조회할 수 있도록 구현되어야 함." 

2. body에 값을 담아서 보내도록 구현을 해두었기 때문에 혼동을 드린 것 같습니다. 죄송합니다. 위에서 Taeho님이 언급해주신 것과 같이 body에 값을 전달받지 않고 쿼리를 통해 전달받도록 변경하기로 했습니다. 추후 반영해놓도록 하겠습니다. 
해당 요청은 지금과 동일하게 GET요청으로 보내주시면 됩니다.

**Comment by joseph0926** [comment]
그러면 쿼리문에 어떤값을 넣고 요청 보내면될까요?

**Comment by Taehoya** [comment]
> 그러면 쿼리문에 어떤값을 넣고 요청 보내면될까요?

넵

**Comment by joseph0926** [comment]
> 넵. (#98)

Backend
```
async function getUserPersonalSchedule(req, res, next) {
  try {
    const { error } = validateScheduleSchema(req.query);
    if (error) return next(new DataFormatError());

    const user = await User.findOne({ where: { nickname: req.nickname } });
    if (!user) {
      return next(new UserNotFoundError());
    }

    const { startDateTime, endDateTime } = req.query;

    const start = moment.utc(startDateTime).toDate();
    const end = moment.utc(endDateTime).toDate();
    const schedule = await PersonalSchedule.getSchedule(user.userId, start, end);
    if (schedule === null) throw new ApiError();
    return res.status(200).json(schedule);
  } catch (err) {
    return next(new ApiError());
  }
}
```

우선 위와 같이 임의로 수정하였습니다

FrontEnd
```
export const getSchedule = createAsyncThunk(
	"schedule/getSchedule",
	async (_, thunkAPI) => {
		const state = thunkAPI.getState();
		const month = state.schedule.month;
		const year = 2023;

		const startDateTime = generateStartDateTime(year, month);
		const endDateTime = generateEndDateTime(year, month);

		try {
			const response = await customFetch.get(
				`/api/user/calendar?startDateTime=${startDateTime.replace(
					".000Z",
					"",
				)}&endDateTime=${endDateTime.replace(".000Z", "")}`,
			);
```

캘린더에서 표시되고있는 월을 가져옵니다 -> 해당 월을 기준으로 시작(01일) 마지막(마지막날)으로 바꿔 쿼리로 날렸습니다
이러면 6월 캘린더 표시시 6월 관련 일정만 표시됩니다

**Comment by Taehoya** [comment]
저기 pr에 있는 branch에 가서 하시면 돼요. backend 수정안하고
